### ISSUE TITLE
Support gotify as notification provider (alternatively apprise)

### ISSUE THREAD

**Issue by TheZoker** [Cybrarist/Discount-Bandit#10]
I know that this application already supports ntfy, but many use gotify instead for their notification management. 
So it would be nice, to also support this. Maybe instead of adding more support for all the different providers, it would also be an option to add support for [Apprise](https://github.com/caronc/apprise). Similar to what [changedetection.io](https://github.com/dgtlmoon/changedetection.io?tab=readme-ov-file#notifications) does. 

Maybe it would be even nice, to allow to configure the notification provider via the UI.

**Comment by Cybrarist** [comment]
i will for sure add apprise to the notification, it's easier and more flexible.

**Comment by Cybrarist** [comment]
supported in v3.2
