### ISSUE TITLE
[Feat Request] Add stores from Spain

### ISSUE THREAD

**Issue by edersong** [Cybrarist/Discount-Bandit#12]
Please, if possible, add stores from Spain:

https://es.wallapop.com/
https://www.mediamarkt.es/
https://www.pccomponentes.com/

**Comment by Cybrarist** [comment]
added to my to do list but i am not sure i can do it for the third one, as i get access denied for my IP, not sure if i can open it from my region

**Comment by Cybrarist** [comment]
i believe  https://www.pccomponentes.com/ is blocked anywhere outside spain? as i can't really access it to check it.

**Comment by edersong** [comment]
Hello, 
Just tested using a VPN connecting from Brasil, for example ,and it worked.
But I have to say that there was a Cloudflare test if I'm a human to access that site, so I think that it can be a problem.

**Comment by Pyromane** [comment]
> i believe https://www.pccomponentes.com/ is blocked anywhere outside spain? as i can't really access it to check it.

Link can be opened with an IP from Austria

**Comment by Cybrarist** [comment]
moved to projects
