### ISSUE TITLE
unable to deploy

### ISSUE THREAD

**Issue by weir1** [Cybrarist/Discount-Bandit#19]
Deployment error
failed to deploy a stack: mysql Pulling discount-bandit Pulling discount-bandit Error Error response from daemon: manifest for cybrarist/discount-bandit:testarm not found: manifest unknown: manifest unknown

**Comment by Cybrarist** [comment]
may i know the steps you have done to get this error ? 

and are you installing using docker or normal web server

**Comment by weir1** [comment]
> may i know the steps you have done to get this error ?
> 
> and are you installing using docker or normal web server

I used portnair as mention in docs
https://discount-bandit.cybrarist.com/installation/compose-portainer.html

**Comment by Cybrarist** [comment]
you are trying to install the image with tag "testarm", i have done that on purpose, so people know which image to install.

please refer to the following url
https://hub.docker.com/r/cybrarist/discount-bandit/tags

and choose the appropriate tag for your server/device.

**Comment by weir1** [comment]
> you are trying to install the image with tag "testarm", i have done that on purpose, so people know which image to install.
> 
> please refer to the following url https://hub.docker.com/r/cybrarist/discount-bandit/tags
> 
> and choose the appropriate tag for your server/device.

oO, I will again try installation today
I hope you support indian ecommerce sites?

**Comment by Cybrarist** [comment]
i think right now i have only amazon, but you can give me a list of ecommerces and i will add them later on

**Comment by weir1** [comment]
Thanks here you goes

1. Amazon India (www.amazon.in)
2. Flipkart (www.flipkart.com)
3. Myntra (www.myntra.com)
4. Snapdeal (www.snapdeal.com)
5. Nykaa (www.nykaa.com)
6. Tata CLiQ (www.tatacliq.com)
7. Ajio (www.ajio.com)
8. Firstcry (www.firstcry.com)
9. Zivame (www.zivame.com)
10. Pepperfry (www.pepperfry.com)

**Comment by Cybrarist** [comment]
- [x] Amazon India ([www.amazon.in](http://www.amazon.in/))
- [x] Flipkart ([www.flipkart.com](http://www.flipkart.com/))
- [x] Myntra ([www.myntra.com](http://www.myntra.com/))

Added in branch 3.2

**Comment by Cybrarist** [comment]
moved to projects
