### ISSUE TITLE
How to run this using compose?

### ISSUE THREAD

**Issue by tismofied** [Cybrarist/Discount-Bandit#22]
I see there is a compose.yaml but I don't see an image in it?

**Comment by Cybrarist** [comment]
you can get the image you want from the following link
https://hub.docker.com/r/cybrarist/discount-bandit

**Comment by tismofied** [comment]
Can I pull by latest?

**Comment by Cybrarist** [comment]
yes you can, but you need to specify the platform so either latest-amd64 or latest-arm.

**Comment by tismofied** [comment]
Sweet. Thank you and free palestine ya rab. 💪

**Comment by tismofied** [comment]
> yes you can, but you need to specify the platform so either latest-amd64 or latest-arm.

The only way I could pull the image was by using `cybrarist/discount-bandit:v3.2-amd64` tag 
latest-amd64 wouldn't work for me. I have docker running on an LXC container in proxmox

**Comment by tismofied** [comment]
> ok, i am not really sure about LXC, but is there any log file or run log file that you can share.

`no matching manifest for linux/amd64 in the manifest list entries`

**Comment by Cybrarist** [comment]
i haven't dealt with dockage before tbh, but it's weird that it doesn't see the amd64. 

can you share with me the full image name , or command passed to download the image and run the container.

**Comment by tismofied** [comment]
> i haven't dealt with dockage before tbh, but it's weird that it doesn't see the amd64.
> 
> can you share with me the full image name , or command passed to download the image and run the container.

ok this weird. I promise I tried like this 2-3 times with latest-amd64 tag and it was throwing that error but now it seems to be working 
![Screenshot 2024-10-25 at 08-30-18 Dockge - 192 168 10 163 5001](https://github.com/user-attachments/assets/6ea8fe72-c15f-4a38-8f61-f9f5c5f3bf28)

**Comment by Cybrarist** [comment]
as long as it works then it's great.
if you encountered the same issue again, please append to this issue with the log so i can investigate further 😄

**Comment by tismofied** [comment]
> as long as it works then it's great.
> 
> if you encountered the same issue again, please append to this issue with the log so i can investigate further 😄 

Will do thank you. 
Since you're in front of your computer, I have another question about ntfy. 
Where do I put my selfhosted server?

**Comment by Cybrarist** [comment]
you can put it on the same machine, as long as it's visible from discount bandit then it will be fine.
