### ISSUE TITLE
RSS and Disable Authentication are not working.

### ISSUE THREAD

**Issue by NeoPlayer13** [Cybrarist/Discount-Bandit#24]
Running in docker compose and the RSS_FEED and DISABLE_AUTH variables in the environment section both have the value 1. I'm assuming that 1=true, but I still tried with 0 and nothing changed.
RSS: adding the path /rss to the base URL returns http code 404 Not Found.

**Comment by Cybrarist** [comment]
did you restart the container after changing the variables ?

**Comment by NeoPlayer13** [comment]
Restarting technically no, but when using docker compose for it to apply the changes with `docker compose up -d`, it automatically recreates the container with the saved changes.

**Comment by Cybrarist** [comment]
you're right, i'll check it

**Comment by mariomaz87** [comment]
Same problem here, thanks!

**Comment by Cybrarist** [comment]
i believe the code is there i just forgot to enable, if you check /app/app/Providers/AppServiceProvider.php 
you should see
//        if (config('settings.disable_auth') && ! app()->runningInConsole())
//            Auth::login(User::first());

if you remove the first two slashes from the lines, it should work. if you need it fast, better than waiting for 3.3

**Comment by NeoPlayer13** [comment]
It has been two weeks since I deployed the app, so I don't remenber if I read it or If I just tried a few different common paths. I tried the path /feed and is working perfectly. Thank you!
