### ISSUE TITLE
Docker container fails to start ("failed to open stream" for autoload.php)

### ISSUE THREAD

**Issue by rmelotte** [Cybrarist/Discount-Bandit#27]
After a fresh clone of the repository, checking out the the `v3.2` branch and running `docker-compose up`, the docker container fails to start.

In the logs, the following warning is repeated:
```
discount-bandit-discount-bandit-1  | 2024-11-14T09:08:16.943448076Z Warning: require(/app/vendor/autoload.php): Failed to open stream: No such file or directory in /app/artisan on line 9
discount-bandit-discount-bandit-1  | 2024-11-14T09:08:16.943463651Z 
discount-bandit-discount-bandit-1  | 2024-11-14T09:08:16.943476572Z Fatal error: Uncaught Error: Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/artisan:9
discount-bandit-discount-bandit-1  | 2024-11-14T09:08:16.943489562Z Stack trace:
discount-bandit-discount-bandit-1  | 2024-11-14T09:08:16.943501925Z #0 {main}
discount-bandit-discount-bandit-1  | 2024-11-14T09:08:16.943513868Z   thrown in /app/artisan on line 9
```

Furthermore, [composer](https://getcomposer.org/), which is mentioned in the README as a dependency, doesn't seem to be installed in the docker container (or it's not in the PATH?).

Am I missing something?

**Comment by Cybrarist** [comment]
if i understood correctly, you cloned the github repo and then ran docker-compose command, right ?

in this case, you need to check your system to make sure it meets the composer packages requirements, as it's not an issue with docker neither the software.

what i would recommend, since docker compose will check your system's requirements to install composer packages, and since you already have docker install, it would be easier to change from to just run docker compose on the docker image instead of building the context.

**Comment by modem7** [comment]
Heya,

On top of this, it seems the readme still states that there is no docker image, and may need updating.

Apologies if I've misread and am incorrect!

**Comment by Cybrarist** [comment]
@modem7 you are correct, i'll fix that

**Comment by rmelotte** [comment]
>if i understood correctly, you cloned the github repo and then ran docker-compose command, right ?

Yes.
I expected to be able to deploy Discount-Bandit by just running `docker-compose up` from a new repository clone.
Wasn't one of the goal of using Docker to avoid having to install packages on the host?

In the end I got it running by installing some more packages and run composer at the container runtime: https://github.com/Cybrarist/Discount-Bandit/pull/31

**Comment by modem7** [comment]
If the container requires packages on the host, then you're doing containers wrong.

All packages should be included within the sandbox of the container.

Only thing that should be on the host are config files etc.

**Comment by Cybrarist** [comment]
the container does not require a package on the host unless you are building it like what he's doing if i understood correctly.

if you want to use docker compose to run the software out of the box, then change the build context to the docker image of your need then report if you are facing errors.

**Comment by rmelotte** [comment]
Yes, using the image from Dockerhub works.
But that does mean that the image on Dockerhub has not simply been built by running docker build on a "bare" repository, right?

Although it's nice for users who cannot afford to build the image to be able to pull it from Dockerhub directly, in my opinion (but I would guess for some other users as well), it's important for users to be able to reproduce the image the image locally as well.
That way, we don't entirely depend on the binary image pushed to Dockerhub, but we have the choice to build the image ourselves as well.

I think for other developers, it's also a lot easier to contribute if they can build and use the image locally (without having to install packages on the host).

**Comment by Cybrarist** [comment]
i think i will close this, as changes will be merged thanks to @rmelotte
