### ISSUE TITLE
Nykaa Blocked by Cloudflare Due to Missing User-Agent

### ISSUE THREAD

**Issue by mrhyperbit** [Cybrarist/Discount-Bandit#28]
When attempting to scrape or interact with Nykaa's product pages, the requests are being blocked by Cloudflare due to the absence of a proper `User-Agent` header in the request. Cloudflare's security system flags requests without a valid `User-Agent` as potential bots, which results in the page being blocked and the following error being returned:

This issue is preventing access to Nykaa's product data through the `Discount-Bandit` tool unless a valid browser-like `User-Agent` is included in the request.

**Steps to Reproduce:**
1. Run the `Discount-Bandit` tool and try to fetch data for a Nykaa product.
2. Observe that the request is blocked by Cloudflare.

**Expected Behavior:**
The request should be able to pass Cloudflare's security filter and return the correct product data.

**Actual Behavior:**
Cloudflare blocks the request due to the lack of a valid `User-Agent` header, resulting in no data being returned.

**Possible Solution:**
Add a valid `User-Agent` header to requests made to Nykaa’s website.

**Comment by Cybrarist** [comment]
may i know which version are you using? which product are you crawling?

also which country are you trying to crawl from

**Comment by mrhyperbit** [comment]
Version: 3.2 (docker, portainer)

Product: CeraVe Face Wash

Country: India

Solution: Just ass a Valid User Agent While crawling it.

**Comment by mrhyperbit** [comment]
Version: 3.2 (docker, portainer)

Product: CeraVe Face Wash

Country: India

Solution: Just add a valid user agent while crawling it.

**Comment by Cybrarist** [comment]
the system already adds a user-agent with the request.
refer to https://github.com/Cybrarist/Discount-Bandit/blob/master/app/Helpers/StoresAvailable/StoreTemplate.php#L485

as for the product, it's crawling fine for me without any issues.
have you ran multiple manual fetching fast ? or did you edit the number of products to crawl ? try to run the system after 24 hours  cooling period.

also can you run a manual fetch, then check for a file called response.html and share it so i can debug further.

**Comment by mrhyperbit** [comment]
I tried a manual curl to the product url, i get same "Attention Required! | Cloudflare, Sorry, you have been blocked"
but if i try curl with a user-agent i get normal response
on manual fetch on discount-bandit the name of the product changes to "Attention Required! | Cloudflare", i tried after 24 hrs, its not time something else is blocking it.
Am running inside a portainer alpine lxc on a proxmox host as a docker compose stack container. anything to do with it? or my ip maybe flagged?

**Comment by Cybrarist** [comment]
no that shouldn't matter, the nykaa crawler uses curl too. 
what happens if you run the following
php artisan test --filter NykaaTest

**Comment by mrhyperbit** [comment]
Its working running locally on development version but not on the proxmox host.
i use docker image (cybrarist/discount-bandit:v3.2-amd64)
probably something to do with the portainer setup?
