### ISSUE TITLE
Docker installation - First user password doesn't work

### ISSUE THREAD

**Issue by stanislasbdx** [Cybrarist/Discount-Bandit#30]
Hi there !
I installed discount-bandit from the Docker Hub image like so : 
```
docker run --name discount-bandit -d \
	-e DB_CONNECTION=mysql \
	-e DB_HOST=10.17.12.88 \
	-e DB_PORT=3306 \
	-e DB_USERNAME=myuser \
	-e DB_PASSWORD="mypasswd" \
	-e DEFAULT_USER=admin \
	-e DEFAULT_EMAIL=admin@stan1712.com \
	-e DEAFULT_PASSWORD="myotherpasswd" \
	-p 3006:80 \
	cybrarist/discount-bandit:latest-amd64
```

But when I try to connect onto the app it says that "These credentials do not match our records."
![image](https://github.com/user-attachments/assets/e9464d5a-d361-4b56-a8eb-8fc007608ff4)

In my db tho I can find my user well created and provided with the email and password (maybe) specified
![image](https://github.com/user-attachments/assets/e9420dba-0102-4369-9b9a-8332d32422af)

Is there a way to solve this ? I've reinstalled multiple times (with deleting the database ofc) and I get the same result...
(even using the environment variable [DISABLE_AUTH=1](https://discount-bandit.cybrarist.com/environments.html#disable-authentication) doesn't seems to work...)

**Comment by NeoPlayer13** [comment]
Did you try erasing the parameters `DEFAULT_USER`, `DEFAULT_EMAIL` and `DEFAULT_PASSWORD` from the `docker run` command and using the [default user credentials](https://discount-bandit.cybrarist.com/environments.html)?

Also you have a typo in the line of `DEFAULT_PASSWORD`, so you should also check if that wasn't what was creating the error.

**Comment by Cybrarist** [comment]
can you share the docker run log to see if there's any error

**Comment by Cybrarist** [comment]
also for auth, it should be fixed in 3.3. not sure if i committed the changes honestly

**Comment by stanislasbdx** [comment]
*I feel silly :sob:*

I didn't saw my typo on the default password......... I fixed it and it works !! 🎉 
And to answer @NeoPlayer13 I tried without the env variables with the default credentials set and it didn't work :/

Anyway thanks to y'all !

**Comment by stratus-ss** [comment]
I am going to review this one because I am having this problem as well. I am loading the envs from a file. I see this:

![image](https://github.com/user-attachments/assets/250cd8a7-a2af-49e2-a5ed-e6d27bc60ac0)

I have cut and paste right out of the env in the container:

```
[stratus@containers ~]$ podman exec -it bandit bash
root@ebeced1dc0c5:/app# env |sort
APPRISE_URL=""
APP_TIMEZONE=UTC
APP_URL="http://containers.example.com:8080"
ASSET_URL="http://containers.example.com:8080"
BREADCRUMBS=1
CHROME_BIN=/usr/bin/chromium-browser
CHROME_OPTS= --disable-dev-shm-usage --headless --disable-gpu --no-sandbox --enable-features=ConversionMeasurement --remote-debugging-port=9222 
DB_CONNECTION=sqlite
DEFAULT_EMAIL="docker@test.com"
DEFAULT_PASSWORD="thisismypassword"
DEFAULT_USER="test"
DISABLE_AUTH=0
DISABLE_TOP_BAR=0
DISPLAY=:99
FRANKENPHP_CONFIG=worker /app/public/index.php
FRANKEN_HOST=localhost
GODEBUG=cgocheck=0
GPG_KEYS=1198C0117593497A5EC5C199286AF1F9897469DC C28D937575603EB4ABB725861C0779DC5C0A9DE4 AFD8691FDAEDF03BDF6E460563F15A9B715376CA
HOME=/root
NTFY_BASE_URL="https://ntfy.sh"
NTFY_CHANNEL_ID=""
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHPIZE_DEPS=autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 	make 		pkg-config 		re2c
PHP_ASC_URL=https://www.php.net/distributions/php-8.3.13.tar.xz.asc
PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
PHP_INI_DIR=/usr/local/etc/php
PHP_LDFLAGS=-Wl,-O1 -pie
PHP_SHA256=89adb978cca209124fe53fd6327bc4966ca21213a7fa2e9504f854e340873018
PHP_URL=https://www.php.net/distributions/php-8.3.13.tar.xz
PHP_VERSION=8.3.13
PWD=/app
RSS_FEED=1
SERVER_NAME=:80
SHLVL=1
SPA=1
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHANNEL_ID=""
TERM=xterm
THEME_COLOR=Stone
TOP_NAVIGATION=0
XDG_CONFIG_HOME=/config
XDG_DATA_HOME=/data
_=/usr/bin/env
container=podman
```

I've tried this with and without DISABLE_AUTH=0 or 1

I am launching it with this command

```
podman run -d -p 8080:80 --name bandit --env-file=bandit_env 16405e8c4e87
```

**Comment by stratus-ss** [comment]
I went ahead and attempted to update the password (assuming that bcrypt is being used)

```
root@dc8d7a3c5a95:/app/database# sqlite3 database.sqlite 
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> select * from users;
1|"test"|"docker@test.com"||$2b$12$n52jdSR8HLlvl2GCtoGTFOiXw9Kx1Wg9yIlKOMRZMhtkTOKhCi8D6||2024-12-21 18:03:54|2024-12-21 18:03:54
sqlite>     
```

```
>>> import bcrypt
>>> 
>>> new_password = "your_new_password"
>>> salt = bcrypt.gensalt(rounds=12)
>>> hashed = bcrypt.hashpw(new_password.encode('utf-8'), salt)
>>> user_id = 1
>>> import sqlite3
>>> c = conn.cursor()
>>> c.execute("UPDATE users SET password = ? WHERE id = ?", (hashed, user_id))
<sqlite3.Cursor object at 0x7f9411357d40>
>>> conn.commit()
>>> conn.close()
>>> hashed
b'$2b$12$zg3xXAuxMHpfYc7F6LtQ8ONG3.D1LDdpFG.9VhtaTAP3IQZiI2Z9u'
```

and I verified that it is now in the user table:

```
root@dc8d7a3c5a95:/app/database# sqlite3 database.sqlite 
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> select * from users;
1|"test"|"docker@test.com"||$2b$12$zg3xXAuxMHpfYc7F6LtQ8ONG3.D1LDdpFG.9VhtaTAP3IQZiI2Z9u||2024-12-21 18:03:54|2024-12-21 18:03:54
```

**Comment by stratus-ss** [comment]
I ran through the same exercise with docker instead of podman on the same host.

```
[root@containers ~]# docker images
REPOSITORY                  TAG            IMAGE ID       CREATED       SIZE
cybrarist/discount-bandit   latest-amd64   16405e8c4e87   5 weeks ago   1.5GB
```
