### ISSUE TITLE
Signal-Cli

### ISSUE THREAD

**Issue by djusHa** [Cybrarist/Discount-Bandit#5]
**Is your feature request related to a problem? Please describe.**
It would be nice to have signal-cli implementation for Notifications. Email is so 80s Stuff

Messages can be sent with a simple Post request to Signal-Cli Docker Container.
It consumes Base64 Encoded Attachments, like Images.

Url of the Project:
https://github.com/bbernhard/signal-cli-rest-api

Example:
```
$ curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' \
     -d '{"message": "Test via Signal API!", "number": "+4412345", "recipients": [ "+44987654" ]}' 
```

API description:
https://bbernhard.github.io/signal-cli-rest-api/

Big THX!

**Comment by Cybrarist** [comment]
i agree, but right now i am working on integrating filament v3, making sure nothing breaks then i would add more features.

**Comment by modem7** [comment]
@djusHa Instead of signal-cli, why not a widely known library such as apprise?

**Comment by Cybrarist** [comment]
well, right now i have ntfy.sh available on the v3-pre so you can use that if you want.

**Comment by djusHa** [comment]
@Cybrarist: Thx
