### ISSUE TITLE
Please add support PostgreSQL

### ISSUE THREAD

**Issue by DocBrown101** [Cybrarist/Discount-Bandit#8]
Hello,

PostgreSQL is the world's most advanced open source database!
Please add support PostgreSQL.
Thanks.

**Comment by Cybrarist** [comment]
but what are the extra benefits that changing the database will bring?

the app is too simple anyway to use any type of database, but you can change it manually if you want to work with postgress. it should be very simple

**Comment by Cybrarist** [comment]
closed for no response, by sqlite is added with the new version.

**Comment by DocBrown101** [comment]
Sorry, I've only just seen that you've replied. Yes sqlite is also a good option as it requires significantly less resources than mysql!
